<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/consume_wallet_tokens_request.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.ConsumeWalletTokensRequest</code>
 */
class ConsumeWalletTokensRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     */
    protected $correlation = null;
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.ConsumptionDetails consumption_details = 2 [json_name = "consumptionDetails"];</code>
     */
    protected $consumption_details = null;
    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 3 [json_name = "tokens"];</code>
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Common\V1\Correlation $correlation
     *     @type \Rphaven\Gsts\V1\ConsumptionDetails $consumption_details
     *     @type array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $tokens
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\ConsumeWalletTokensRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     * @return \Rphaven\Common\V1\Correlation|null
     */
    public function getCorrelation()
    {
        return $this->correlation;
    }

    public function hasCorrelation()
    {
        return isset($this->correlation);
    }

    public function clearCorrelation()
    {
        unset($this->correlation);
    }

    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     * @param \Rphaven\Common\V1\Correlation $var
     * @return $this
     */
    public function setCorrelation($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Common\V1\Correlation::class);
        $this->correlation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.ConsumptionDetails consumption_details = 2 [json_name = "consumptionDetails"];</code>
     * @return \Rphaven\Gsts\V1\ConsumptionDetails|null
     */
    public function getConsumptionDetails()
    {
        return $this->consumption_details;
    }

    public function hasConsumptionDetails()
    {
        return isset($this->consumption_details);
    }

    public function clearConsumptionDetails()
    {
        unset($this->consumption_details);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.ConsumptionDetails consumption_details = 2 [json_name = "consumptionDetails"];</code>
     * @param \Rphaven\Gsts\V1\ConsumptionDetails $var
     * @return $this
     */
    public function setConsumptionDetails($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\ConsumptionDetails::class);
        $this->consumption_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 3 [json_name = "tokens"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 3 [json_name = "tokens"];</code>
     * @param array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rphaven\Gsts\V1\Token::class);
        $this->tokens = $arr;

        return $this;
    }

}

