<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gsts/v1/member_sub.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.ConsumeMemberToken</code>
 */
class ConsumeMemberToken extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.ConsumptionDetails consumption_details = 1 [json_name = "consumptionDetails"];</code>
     */
    protected $consumption_details = null;
    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 2 [json_name = "tokens"];</code>
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Gsts\V1\ConsumptionDetails $consumption_details
     *     @type array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $tokens
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\MemberSub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.ConsumptionDetails consumption_details = 1 [json_name = "consumptionDetails"];</code>
     * @return \Rphaven\Gsts\V1\ConsumptionDetails|null
     */
    public function getConsumptionDetails()
    {
        return $this->consumption_details;
    }

    public function hasConsumptionDetails()
    {
        return isset($this->consumption_details);
    }

    public function clearConsumptionDetails()
    {
        unset($this->consumption_details);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.ConsumptionDetails consumption_details = 1 [json_name = "consumptionDetails"];</code>
     * @param \Rphaven\Gsts\V1\ConsumptionDetails $var
     * @return $this
     */
    public function setConsumptionDetails($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\ConsumptionDetails::class);
        $this->consumption_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 2 [json_name = "tokens"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 2 [json_name = "tokens"];</code>
     * @param array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rphaven\Gsts\V1\Token::class);
        $this->tokens = $arr;

        return $this;
    }

}

