<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gsts/v1/member_sub.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.ConsumptionDetails</code>
 */
class ConsumptionDetails extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Wallet wallet = 1 [json_name = "wallet"];</code>
     */
    protected $wallet = null;
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member volunteer = 2 [json_name = "volunteer"];</code>
     */
    protected $volunteer = null;
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Meet meet = 3 [json_name = "meet"];</code>
     */
    protected $meet = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Gsts\V1\Wallet $wallet
     *     @type \Rphaven\Gsts\V1\Member $volunteer
     *     @type \Rphaven\Gsts\V1\Meet $meet
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\MemberSub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Wallet wallet = 1 [json_name = "wallet"];</code>
     * @return \Rphaven\Gsts\V1\Wallet|null
     */
    public function getWallet()
    {
        return $this->wallet;
    }

    public function hasWallet()
    {
        return isset($this->wallet);
    }

    public function clearWallet()
    {
        unset($this->wallet);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Wallet wallet = 1 [json_name = "wallet"];</code>
     * @param \Rphaven\Gsts\V1\Wallet $var
     * @return $this
     */
    public function setWallet($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Wallet::class);
        $this->wallet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member volunteer = 2 [json_name = "volunteer"];</code>
     * @return \Rphaven\Gsts\V1\Member|null
     */
    public function getVolunteer()
    {
        return $this->volunteer;
    }

    public function hasVolunteer()
    {
        return isset($this->volunteer);
    }

    public function clearVolunteer()
    {
        unset($this->volunteer);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member volunteer = 2 [json_name = "volunteer"];</code>
     * @param \Rphaven\Gsts\V1\Member $var
     * @return $this
     */
    public function setVolunteer($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Member::class);
        $this->volunteer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Meet meet = 3 [json_name = "meet"];</code>
     * @return \Rphaven\Gsts\V1\Meet|null
     */
    public function getMeet()
    {
        return $this->meet;
    }

    public function hasMeet()
    {
        return isset($this->meet);
    }

    public function clearMeet()
    {
        unset($this->meet);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Meet meet = 3 [json_name = "meet"];</code>
     * @param \Rphaven\Gsts\V1\Meet $var
     * @return $this
     */
    public function setMeet($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Meet::class);
        $this->meet = $var;

        return $this;
    }

}

