<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gsts/v1/member_sub.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.ConsumeMemberToken</code>
 */
class ConsumeMemberToken extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member member = 1 [json_name = "member"];</code>
     */
    protected $member = null;
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member volunteer = 2 [json_name = "volunteer"];</code>
     */
    protected $volunteer = null;
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Meet meet = 3 [json_name = "meet"];</code>
     */
    protected $meet = null;
    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 4 [json_name = "tokens"];</code>
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Gsts\V1\Member $member
     *     @type \Rphaven\Gsts\V1\Member $volunteer
     *     @type \Rphaven\Gsts\V1\Meet $meet
     *     @type array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $tokens
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\MemberSub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member member = 1 [json_name = "member"];</code>
     * @return \Rphaven\Gsts\V1\Member|null
     */
    public function getMember()
    {
        return $this->member;
    }

    public function hasMember()
    {
        return isset($this->member);
    }

    public function clearMember()
    {
        unset($this->member);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member member = 1 [json_name = "member"];</code>
     * @param \Rphaven\Gsts\V1\Member $var
     * @return $this
     */
    public function setMember($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Member::class);
        $this->member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member volunteer = 2 [json_name = "volunteer"];</code>
     * @return \Rphaven\Gsts\V1\Member|null
     */
    public function getVolunteer()
    {
        return $this->volunteer;
    }

    public function hasVolunteer()
    {
        return isset($this->volunteer);
    }

    public function clearVolunteer()
    {
        unset($this->volunteer);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member volunteer = 2 [json_name = "volunteer"];</code>
     * @param \Rphaven\Gsts\V1\Member $var
     * @return $this
     */
    public function setVolunteer($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Member::class);
        $this->volunteer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Meet meet = 3 [json_name = "meet"];</code>
     * @return \Rphaven\Gsts\V1\Meet|null
     */
    public function getMeet()
    {
        return $this->meet;
    }

    public function hasMeet()
    {
        return isset($this->meet);
    }

    public function clearMeet()
    {
        unset($this->meet);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Meet meet = 3 [json_name = "meet"];</code>
     * @param \Rphaven\Gsts\V1\Meet $var
     * @return $this
     */
    public function setMeet($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Meet::class);
        $this->meet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 4 [json_name = "tokens"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 4 [json_name = "tokens"];</code>
     * @param array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rphaven\Gsts\V1\Token::class);
        $this->tokens = $arr;

        return $this;
    }

}

