<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: rphaven/gsts/v1/consume_wallet_tokens_service.proto

namespace Rphaven\Gsts\V1;

use Spiral\RoadRunner\GRPC;

interface ConsumeWalletTokensServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "rphaven.gsts.v1.ConsumeWalletTokensService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ConsumeWalletTokensRequest $in
    * @return ConsumeWalletTokensResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function ConsumeWalletTokens(GRPC\ContextInterface $ctx, ConsumeWalletTokensRequest $in): ConsumeWalletTokensResponse;
}
