<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/issue_wallet_tokens_request.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.IssueWalletTokensRequest</code>
 */
class IssueWalletTokensRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     */
    protected $correlation = null;
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Wallet wallet = 2 [json_name = "wallet"];</code>
     */
    protected $wallet = null;
    /**
     * Generated from protobuf field <code>sint32 number = 3 [json_name = "number"];</code>
     */
    protected $number = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Common\V1\Correlation $correlation
     *     @type \Rphaven\Gsts\V1\Wallet $wallet
     *     @type int $number
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\IssueWalletTokensRequest::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     * @return \Rphaven\Common\V1\Correlation|null
     */
    public function getCorrelation()
    {
        return $this->correlation;
    }

    public function hasCorrelation()
    {
        return isset($this->correlation);
    }

    public function clearCorrelation()
    {
        unset($this->correlation);
    }

    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Correlation correlation = 1 [json_name = "correlation"];</code>
     * @param \Rphaven\Common\V1\Correlation $var
     * @return $this
     */
    public function setCorrelation($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Common\V1\Correlation::class);
        $this->correlation = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Wallet wallet = 2 [json_name = "wallet"];</code>
     * @return \Rphaven\Gsts\V1\Wallet|null
     */
    public function getWallet()
    {
        return $this->wallet;
    }

    public function hasWallet()
    {
        return isset($this->wallet);
    }

    public function clearWallet()
    {
        unset($this->wallet);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Wallet wallet = 2 [json_name = "wallet"];</code>
     * @param \Rphaven\Gsts\V1\Wallet $var
     * @return $this
     */
    public function setWallet($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Wallet::class);
        $this->wallet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 number = 3 [json_name = "number"];</code>
     * @return int
     */
    public function getNumber()
    {
        return $this->number;
    }

    /**
     * Generated from protobuf field <code>sint32 number = 3 [json_name = "number"];</code>
     * @param int $var
     * @return $this
     */
    public function setNumber($var)
    {
        GPBUtil::checkInt32($var);
        $this->number = $var;

        return $this;
    }

}

