<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: rphaven/gsts/v1/issue_wallet_tokens_service.proto

namespace Rphaven\Gsts\V1;

use Spiral\RoadRunner\GRPC;

interface IssueWalletTokensServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "rphaven.gsts.v1.IssueWalletTokensService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param IssueWalletTokensRequest $in
    * @return IssueWalletTokensResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function IssueWalletTokens(GRPC\ContextInterface $ctx, IssueWalletTokensRequest $in): IssueWalletTokensResponse;
}
