<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gsts/v1/token.proto

namespace Rphaven\Gsts\V1;

use UnexpectedValueException;

/**
 * Protobuf type <code>rphaven.gsts.v1.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>TOKEN_ISSUED = 0;</code>
     */
    const TOKEN_ISSUED = 0;
    /**
     * Generated from protobuf enum <code>TOKEN_CONSUMED = 1;</code>
     */
    const TOKEN_CONSUMED = 1;

    private static $valueToName = [
        self::TOKEN_ISSUED => 'TOKEN_ISSUED',
        self::TOKEN_CONSUMED => 'TOKEN_CONSUMED',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

