<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: gsts/v1/subs.proto

namespace Rphaven\Gsts\V1;

use Spiral\RoadRunner\GRPC;

interface SubsServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "rphaven.gsts.v1.SubsService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param ConsumeMemberToken $in
    * @return TokenConsumption
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Session(GRPC\ContextInterface $ctx, ConsumeMemberToken $in): TokenConsumption;
}
