<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/tokens_not_issued.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.TokensNotIssued</code>
 */
class TokensNotIssued extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.TokenIssueTransaction transaction = 1 [json_name = "transaction"];</code>
     */
    protected $transaction = null;
    /**
     * Generated from protobuf field <code>repeated .rphaven.common.v1.Error errors = 2 [json_name = "errors"];</code>
     */
    private $errors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Gsts\V1\TokenIssueTransaction $transaction
     *     @type array<\Rphaven\Common\V1\Error>|\Google\Protobuf\Internal\RepeatedField $errors
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\TokensNotIssued::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.TokenIssueTransaction transaction = 1 [json_name = "transaction"];</code>
     * @return \Rphaven\Gsts\V1\TokenIssueTransaction|null
     */
    public function getTransaction()
    {
        return $this->transaction;
    }

    public function hasTransaction()
    {
        return isset($this->transaction);
    }

    public function clearTransaction()
    {
        unset($this->transaction);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.TokenIssueTransaction transaction = 1 [json_name = "transaction"];</code>
     * @param \Rphaven\Gsts\V1\TokenIssueTransaction $var
     * @return $this
     */
    public function setTransaction($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\TokenIssueTransaction::class);
        $this->transaction = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.common.v1.Error errors = 2 [json_name = "errors"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->errors;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.common.v1.Error errors = 2 [json_name = "errors"];</code>
     * @param array<\Rphaven\Common\V1\Error>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rphaven\Common\V1\Error::class);
        $this->errors = $arr;

        return $this;
    }

}

