<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/token_consumption_transaction.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.TokenConsumptionTransaction</code>
 */
class TokenConsumptionTransaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Uid id = 1 [json_name = "id"];</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    protected $timestamp = null;
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.ConsumptionDetails consumption_details = 3 [json_name = "consumptionDetails"];</code>
     */
    protected $consumption_details = null;
    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 4 [json_name = "tokens"];</code>
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Common\V1\Uid $id
     *     @type \Google\Protobuf\Timestamp $timestamp
     *     @type \Rphaven\Gsts\V1\ConsumptionDetails $consumption_details
     *     @type array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $tokens
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\TokenConsumptionTransaction::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Uid id = 1 [json_name = "id"];</code>
     * @return \Rphaven\Common\V1\Uid|null
     */
    public function getId()
    {
        return $this->id;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Uid id = 1 [json_name = "id"];</code>
     * @param \Rphaven\Common\V1\Uid $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Common\V1\Uid::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.ConsumptionDetails consumption_details = 3 [json_name = "consumptionDetails"];</code>
     * @return \Rphaven\Gsts\V1\ConsumptionDetails|null
     */
    public function getConsumptionDetails()
    {
        return $this->consumption_details;
    }

    public function hasConsumptionDetails()
    {
        return isset($this->consumption_details);
    }

    public function clearConsumptionDetails()
    {
        unset($this->consumption_details);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.ConsumptionDetails consumption_details = 3 [json_name = "consumptionDetails"];</code>
     * @param \Rphaven\Gsts\V1\ConsumptionDetails $var
     * @return $this
     */
    public function setConsumptionDetails($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\ConsumptionDetails::class);
        $this->consumption_details = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 4 [json_name = "tokens"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 4 [json_name = "tokens"];</code>
     * @param array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rphaven\Gsts\V1\Token::class);
        $this->tokens = $arr;

        return $this;
    }

}

