<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gsts/v1/member_sub.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.TokenTransaction</code>
 */
class TokenTransaction extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes transaction_id = 1 [json_name = "transactionId"];</code>
     */
    protected $transaction_id = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    protected $timestamp = null;
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member member = 3 [json_name = "member"];</code>
     */
    protected $member = null;
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member volunteer = 4 [json_name = "volunteer"];</code>
     */
    protected $volunteer = null;
    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 5 [json_name = "tokens"];</code>
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $transaction_id
     *     @type \Google\Protobuf\Timestamp $timestamp
     *     @type \Rphaven\Gsts\V1\Member $member
     *     @type \Rphaven\Gsts\V1\Member $volunteer
     *     @type array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $tokens
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\MemberSub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes transaction_id = 1 [json_name = "transactionId"];</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_id = 1 [json_name = "transactionId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->transaction_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member member = 3 [json_name = "member"];</code>
     * @return \Rphaven\Gsts\V1\Member|null
     */
    public function getMember()
    {
        return $this->member;
    }

    public function hasMember()
    {
        return isset($this->member);
    }

    public function clearMember()
    {
        unset($this->member);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member member = 3 [json_name = "member"];</code>
     * @param \Rphaven\Gsts\V1\Member $var
     * @return $this
     */
    public function setMember($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Member::class);
        $this->member = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member volunteer = 4 [json_name = "volunteer"];</code>
     * @return \Rphaven\Gsts\V1\Member|null
     */
    public function getVolunteer()
    {
        return $this->volunteer;
    }

    public function hasVolunteer()
    {
        return isset($this->volunteer);
    }

    public function clearVolunteer()
    {
        unset($this->volunteer);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Member volunteer = 4 [json_name = "volunteer"];</code>
     * @param \Rphaven\Gsts\V1\Member $var
     * @return $this
     */
    public function setVolunteer($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Member::class);
        $this->volunteer = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 5 [json_name = "tokens"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 5 [json_name = "tokens"];</code>
     * @param array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rphaven\Gsts\V1\Token::class);
        $this->tokens = $arr;

        return $this;
    }

}

