<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gsts/v1/member_sub.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.TokenConsumption</code>
 */
class TokenConsumption extends \Google\Protobuf\Internal\Message
{
    protected $result;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Gsts\V1\TokensConsumed $success
     *     @type \Rphaven\Gsts\V1\TokensNotConsumed $error
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\MemberSub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.TokensConsumed success = 1 [json_name = "success"];</code>
     * @return \Rphaven\Gsts\V1\TokensConsumed|null
     */
    public function getSuccess()
    {
        return $this->readOneof(1);
    }

    public function hasSuccess()
    {
        return $this->hasOneof(1);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.TokensConsumed success = 1 [json_name = "success"];</code>
     * @param \Rphaven\Gsts\V1\TokensConsumed $var
     * @return $this
     */
    public function setSuccess($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\TokensConsumed::class);
        $this->writeOneof(1, $var);

        return $this;
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.TokensNotConsumed error = 2 [json_name = "error"];</code>
     * @return \Rphaven\Gsts\V1\TokensNotConsumed|null
     */
    public function getError()
    {
        return $this->readOneof(2);
    }

    public function hasError()
    {
        return $this->hasOneof(2);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.TokensNotConsumed error = 2 [json_name = "error"];</code>
     * @param \Rphaven\Gsts\V1\TokensNotConsumed $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\TokensNotConsumed::class);
        $this->writeOneof(2, $var);

        return $this;
    }

    /**
     * @return string
     */
    public function getResult()
    {
        return $this->whichOneof("result");
    }

}

