<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/venue_meet.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.VenueMeet</code>
 */
class VenueMeet extends \Google\Protobuf\Internal\Message
{
    /**
     * The latitude in degrees. It must be in the range [-90.0, +90.0].
     *
     * Generated from protobuf field <code>double latitude = 1 [json_name = "latitude"];</code>
     */
    protected $latitude = 0.0;
    /**
     * The longitude in degrees. It must be in the range [-180.0, +180.0].
     *
     * Generated from protobuf field <code>double longitude = 2 [json_name = "longitude"];</code>
     */
    protected $longitude = 0.0;
    /**
     * Generated from protobuf field <code>int32 accuracy = 3 [json_name = "accuracy"];</code>
     */
    protected $accuracy = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type float $latitude
     *           The latitude in degrees. It must be in the range [-90.0, +90.0].
     *     @type float $longitude
     *           The longitude in degrees. It must be in the range [-180.0, +180.0].
     *     @type int $accuracy
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\VenueMeet::initOnce();
        parent::__construct($data);
    }

    /**
     * The latitude in degrees. It must be in the range [-90.0, +90.0].
     *
     * Generated from protobuf field <code>double latitude = 1 [json_name = "latitude"];</code>
     * @return float
     */
    public function getLatitude()
    {
        return $this->latitude;
    }

    /**
     * The latitude in degrees. It must be in the range [-90.0, +90.0].
     *
     * Generated from protobuf field <code>double latitude = 1 [json_name = "latitude"];</code>
     * @param float $var
     * @return $this
     */
    public function setLatitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->latitude = $var;

        return $this;
    }

    /**
     * The longitude in degrees. It must be in the range [-180.0, +180.0].
     *
     * Generated from protobuf field <code>double longitude = 2 [json_name = "longitude"];</code>
     * @return float
     */
    public function getLongitude()
    {
        return $this->longitude;
    }

    /**
     * The longitude in degrees. It must be in the range [-180.0, +180.0].
     *
     * Generated from protobuf field <code>double longitude = 2 [json_name = "longitude"];</code>
     * @param float $var
     * @return $this
     */
    public function setLongitude($var)
    {
        GPBUtil::checkDouble($var);
        $this->longitude = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 accuracy = 3 [json_name = "accuracy"];</code>
     * @return int
     */
    public function getAccuracy()
    {
        return $this->accuracy;
    }

    /**
     * Generated from protobuf field <code>int32 accuracy = 3 [json_name = "accuracy"];</code>
     * @param int $var
     * @return $this
     */
    public function setAccuracy($var)
    {
        GPBUtil::checkInt32($var);
        $this->accuracy = $var;

        return $this;
    }

}

