<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/wallet_tokens.proto

namespace Rphaven\Gsts\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.v1.WalletTokens</code>
 */
class WalletTokens extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Wallet wallet = 1 [json_name = "wallet"];</code>
     */
    protected $wallet = null;
    /**
     * Generated from protobuf field <code>sint32 total = 2 [json_name = "total"];</code>
     */
    protected $total = 0;
    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 3 [json_name = "tokens"];</code>
     */
    private $tokens;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Gsts\V1\Wallet $wallet
     *     @type int $total
     *     @type array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $tokens
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Gsts\V1\GPBMetadata\WalletTokens::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Wallet wallet = 1 [json_name = "wallet"];</code>
     * @return \Rphaven\Gsts\V1\Wallet|null
     */
    public function getWallet()
    {
        return $this->wallet;
    }

    public function hasWallet()
    {
        return isset($this->wallet);
    }

    public function clearWallet()
    {
        unset($this->wallet);
    }

    /**
     * Generated from protobuf field <code>.rphaven.gsts.v1.Wallet wallet = 1 [json_name = "wallet"];</code>
     * @param \Rphaven\Gsts\V1\Wallet $var
     * @return $this
     */
    public function setWallet($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Gsts\V1\Wallet::class);
        $this->wallet = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sint32 total = 2 [json_name = "total"];</code>
     * @return int
     */
    public function getTotal()
    {
        return $this->total;
    }

    /**
     * Generated from protobuf field <code>sint32 total = 2 [json_name = "total"];</code>
     * @param int $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkInt32($var);
        $this->total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 3 [json_name = "tokens"];</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getTokens()
    {
        return $this->tokens;
    }

    /**
     * Generated from protobuf field <code>repeated .rphaven.gsts.v1.Token tokens = 3 [json_name = "tokens"];</code>
     * @param array<\Rphaven\Gsts\V1\Token>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setTokens($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Rphaven\Gsts\V1\Token::class);
        $this->tokens = $arr;

        return $this;
    }

}

