version: '3.5'

services:
  grpc:
    build:
      context: ./
      dockerfile: dev/docker/php/Dockerfile
      target: proto
      args:
        GITHUB_TOKEN: "${GITHUB_TOKEN}"
    environment:
      - "SUBS_SERVER=${SUBS_SERVER}"
    volumes:
      - ./:/RPHaven
    networks:
      default:

networks:
  default:
    name: grpc
    external: true