<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/member_sub.proto

namespace RpHaven\Protobuf\Gsts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.MemberSub</code>
 */
class MemberSub extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bytes volunteer_id = 1 [json_name = "volunteerId"];</code>
     */
    protected $volunteer_id = '';
    /**
     * Generated from protobuf field <code>string member_uri = 2 [json_name = "memberUri"];</code>
     */
    protected $member_uri = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $volunteer_id
     *     @type string $member_uri
     * }
     */
    public function __construct($data = NULL) {
        \RpHaven\Protobuf\Metadata\Gsts\MemberSub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bytes volunteer_id = 1 [json_name = "volunteerId"];</code>
     * @return string
     */
    public function getVolunteerId()
    {
        return $this->volunteer_id;
    }

    /**
     * Generated from protobuf field <code>bytes volunteer_id = 1 [json_name = "volunteerId"];</code>
     * @param string $var
     * @return $this
     */
    public function setVolunteerId($var)
    {
        GPBUtil::checkString($var, False);
        $this->volunteer_id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_uri = 2 [json_name = "memberUri"];</code>
     * @return string
     */
    public function getMemberUri()
    {
        return $this->member_uri;
    }

    /**
     * Generated from protobuf field <code>string member_uri = 2 [json_name = "memberUri"];</code>
     * @param string $var
     * @return $this
     */
    public function setMemberUri($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_uri = $var;

        return $this;
    }

}

