<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/member_sub.proto

namespace RpHaven\Protobuf\Gsts;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.gsts.SubAccepted</code>
 */
class SubAccepted extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 tokens_remaining = 1 [json_name = "tokensRemaining"];</code>
     */
    protected $tokens_remaining = 0;
    /**
     * Generated from protobuf field <code>string volunteer_name = 2 [json_name = "volunteerName"];</code>
     */
    protected $volunteer_name = '';
    /**
     * Generated from protobuf field <code>string member_name = 3 [json_name = "memberName"];</code>
     */
    protected $member_name = '';
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 4 [json_name = "lastUpdated"];</code>
     */
    protected $last_updated = null;
    /**
     * Generated from protobuf field <code>bytes transaction_id = 5 [json_name = "transactionId"];</code>
     */
    protected $transaction_id = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $tokens_remaining
     *     @type string $volunteer_name
     *     @type string $member_name
     *     @type \Google\Protobuf\Timestamp $last_updated
     *     @type string $transaction_id
     * }
     */
    public function __construct($data = NULL) {
        \RpHaven\Protobuf\Metadata\Gsts\MemberSub::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 tokens_remaining = 1 [json_name = "tokensRemaining"];</code>
     * @return int
     */
    public function getTokensRemaining()
    {
        return $this->tokens_remaining;
    }

    /**
     * Generated from protobuf field <code>int32 tokens_remaining = 1 [json_name = "tokensRemaining"];</code>
     * @param int $var
     * @return $this
     */
    public function setTokensRemaining($var)
    {
        GPBUtil::checkInt32($var);
        $this->tokens_remaining = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string volunteer_name = 2 [json_name = "volunteerName"];</code>
     * @return string
     */
    public function getVolunteerName()
    {
        return $this->volunteer_name;
    }

    /**
     * Generated from protobuf field <code>string volunteer_name = 2 [json_name = "volunteerName"];</code>
     * @param string $var
     * @return $this
     */
    public function setVolunteerName($var)
    {
        GPBUtil::checkString($var, True);
        $this->volunteer_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string member_name = 3 [json_name = "memberName"];</code>
     * @return string
     */
    public function getMemberName()
    {
        return $this->member_name;
    }

    /**
     * Generated from protobuf field <code>string member_name = 3 [json_name = "memberName"];</code>
     * @param string $var
     * @return $this
     */
    public function setMemberName($var)
    {
        GPBUtil::checkString($var, True);
        $this->member_name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 4 [json_name = "lastUpdated"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getLastUpdated()
    {
        return $this->last_updated;
    }

    public function hasLastUpdated()
    {
        return isset($this->last_updated);
    }

    public function clearLastUpdated()
    {
        unset($this->last_updated);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp last_updated = 4 [json_name = "lastUpdated"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setLastUpdated($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->last_updated = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_id = 5 [json_name = "transactionId"];</code>
     * @return string
     */
    public function getTransactionId()
    {
        return $this->transaction_id;
    }

    /**
     * Generated from protobuf field <code>bytes transaction_id = 5 [json_name = "transactionId"];</code>
     * @param string $var
     * @return $this
     */
    public function setTransactionId($var)
    {
        GPBUtil::checkString($var, False);
        $this->transaction_id = $var;

        return $this;
    }

}

