<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: rphaven/gsts/v1/subs.proto

namespace RpHaven\Protobuf\Gsts;

use Spiral\RoadRunner\GRPC;

interface SubsServiceInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "rphaven.gsts.v1.SubsService";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param MemberSub $in
    * @return SubAccepted
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function Session(GRPC\ContextInterface $ctx, MemberSub $in): SubAccepted;
}
