<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/common/v1/correlation.proto

namespace Rphaven\Common\V1;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>rphaven.common.v1.Correlation</code>
 */
class Correlation extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Uid id = 1 [json_name = "id"];</code>
     */
    protected $id = null;
    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     */
    protected $timestamp = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Rphaven\Common\V1\Uid $id
     *     @type \Google\Protobuf\Timestamp $timestamp
     * }
     */
    public function __construct($data = NULL) {
        \Rphaven\Common\V1\GPBMetadata\Correlation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Uid id = 1 [json_name = "id"];</code>
     * @return \Rphaven\Common\V1\Uid|null
     */
    public function getId()
    {
        return $this->id;
    }

    public function hasId()
    {
        return isset($this->id);
    }

    public function clearId()
    {
        unset($this->id);
    }

    /**
     * Generated from protobuf field <code>.rphaven.common.v1.Uid id = 1 [json_name = "id"];</code>
     * @param \Rphaven\Common\V1\Uid $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkMessage($var, \Rphaven\Common\V1\Uid::class);
        $this->id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @return \Google\Protobuf\Timestamp|null
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    public function hasTimestamp()
    {
        return isset($this->timestamp);
    }

    public function clearTimestamp()
    {
        unset($this->timestamp);
    }

    /**
     * Generated from protobuf field <code>.google.protobuf.Timestamp timestamp = 2 [json_name = "timestamp"];</code>
     * @param \Google\Protobuf\Timestamp $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Google\Protobuf\Timestamp::class);
        $this->timestamp = $var;

        return $this;
    }

}

