<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/common/v1/correlation.proto

namespace Rphaven\Common\V1\GPBMetadata;

class Correlation
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \Rphaven\Common\V1\GPBMetadata\Uid::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xE0\x02\x0A#rphaven/common/v1/correlation.proto\x12\x11rphaven.common.v1\x1A\x1Brphaven/common/v1/uid.proto\"o\x0A\x0BCorrelation\x12&\x0A\x02id\x18\x01 \x01(\x0B2\x16.rphaven.common.v1.UidR\x02id\x128\x0A\x09timestamp\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampR\x09timestampB\x8F\x01\x0A\x15com.rphaven.common.v1B\x10CorrelationProtoP\x01\xA2\x02\x03RCX\xAA\x02\x11Rphaven.Common.V1\xCA\x02\x11Rphaven\\Common\\V1\xE2\x02\x1DRphaven\\Common\\V1\\GPBMetadata\xEA\x02\x13Rphaven::Common::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

