<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/common/v1/error.proto

namespace Rphaven\Common\V1\GPBMetadata;

class Error
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \Rphaven\Common\V1\GPBMetadata\Uid::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x89\x03\x0A\x1Drphaven/common/v1/error.proto\x12\x11rphaven.common.v1\x1A\x1Brphaven/common/v1/uid.proto\"\xA3\x01\x0A\x05Error\x12&\x0A\x02id\x18\x01 \x01(\x0B2\x16.rphaven.common.v1.UidR\x02id\x128\x0A\x09timestamp\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampR\x09timestamp\x12\x16\x0A\x06reason\x18\x03 \x01(\x09R\x06reason\x12\x17\x0A\x04code\x18\x04 \x01(\x11H\x00R\x04code\x88\x01\x01B\x07\x0A\x05_codeB\x89\x01\x0A\x15com.rphaven.common.v1B\x0AErrorProtoP\x01\xA2\x02\x03RCX\xAA\x02\x11Rphaven.Common.V1\xCA\x02\x11Rphaven\\Common\\V1\xE2\x02\x1DRphaven\\Common\\V1\\GPBMetadata\xEA\x02\x13Rphaven::Common::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

