<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/member_sub.proto

namespace RpHaven\Protobuf\Metadata\Gsts;

class MemberSub
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xF5\x03\x0A rphaven/gsts/v1/member_sub.proto\x12\x0Crphaven.gsts\"M\x0A\x09MemberSub\x12!\x0A\x0Cvolunteer_id\x18\x01 \x01(\x0CR\x0BvolunteerId\x12\x1D\x0A\x0Amember_uri\x18\x02 \x01(\x09R\x09memberUri\"\xE6\x01\x0A\x0BSubAccepted\x12)\x0A\x10tokens_remaining\x18\x01 \x01(\x05R\x0FtokensRemaining\x12%\x0A\x0Evolunteer_name\x18\x02 \x01(\x09R\x0DvolunteerName\x12\x1F\x0A\x0Bmember_name\x18\x03 \x01(\x09R\x0AmemberName\x12=\x0A\x0Clast_updated\x18\x04 \x01(\x0B2\x1A.google.protobuf.TimestampR\x0BlastUpdated\x12%\x0A\x0Etransaction_id\x18\x05 \x01(\x0CR\x0DtransactionIdB\x82\x01\x0A\x10com.rphaven.gstsB\x0EMemberSubProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0CRphaven.Gsts\xCA\x02\x15RpHaven\\Protobuf\\Gsts\xE2\x02\x1ERpHaven\\Protobuf\\Metadata\\Gsts\xEA\x02\x0DRphaven::Gstsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

