<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/subs.proto

namespace RpHaven\Protobuf\Metadata\Gsts;

class Subs
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \RpHaven\Protobuf\Metadata\Gsts\MemberSub::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x81\x02\x0A\x1Arphaven/gsts/v1/subs.proto\x12\x0Crphaven.gsts2N\x0A\x0BSubsService\x12?\x0A\x07Session\x12\x17.rphaven.gsts.MemberSub\x1A\x19.rphaven.gsts.SubAccepted\"\x00B}\x0A\x10com.rphaven.gstsB\x09SubsProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0CRphaven.Gsts\xCA\x02\x15RpHaven\\Protobuf\\Gsts\xE2\x02\x1ERpHaven\\Protobuf\\Metadata\\Gsts\xEA\x02\x0DRphaven::Gstsb\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

