<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/consume_wallet_tokens_response.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class ConsumeWalletTokensResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Rphaven\Common\V1\GPBMetadata\Correlation::initOnce();
        \Rphaven\Gsts\V1\GPBMetadata\TokensConsumed::initOnce();
        \Rphaven\Gsts\V1\GPBMetadata\TokensNotConsumed::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x9E\x04\x0A4rphaven/gsts/v1/consume_wallet_tokens_response.proto\x12\x0Frphaven.gsts.v1\x1A%rphaven/gsts/v1/tokens_consumed.proto\x1A)rphaven/gsts/v1/tokens_not_consumed.proto\"\xE2\x01\x0A\x1BConsumeWalletTokensResponse\x12@\x0A\x0Bcorrelation\x18\x01 \x01(\x0B2\x1E.rphaven.common.v1.CorrelationR\x0Bcorrelation\x12;\x0A\x07success\x18\x02 \x01(\x0B2\x1F.rphaven.gsts.v1.TokensConsumedH\x00R\x07success\x12:\x0A\x05error\x18\x03 \x01(\x0B2\".rphaven.gsts.v1.TokensNotConsumedH\x00R\x05errorB\x08\x0A\x06resultB\x95\x01\x0A\x13com.rphaven.gsts.v1B ConsumeWalletTokensResponseProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

