<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/create_member_wallets_request.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class CreateMemberWalletsRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Rphaven\Common\V1\GPBMetadata\Correlation::initOnce();
        \Rphaven\Gsts\V1\GPBMetadata\Member::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x95\x03\x0A3rphaven/gsts/v1/create_member_wallets_request.proto\x12\x0Frphaven.gsts.v1\x1A\x1Crphaven/gsts/v1/member.proto\"\x8F\x01\x0A\x1ACreateMemberWalletsRequest\x12@\x0A\x0Bcorrelation\x18\x01 \x01(\x0B2\x1E.rphaven.common.v1.CorrelationR\x0Bcorrelation\x12/\x0A\x06member\x18\x02 \x01(\x0B2\x17.rphaven.gsts.v1.MemberR\x06memberB\x94\x01\x0A\x13com.rphaven.gsts.v1B\x1FCreateMemberWalletsRequestProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

