<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/create_member_wallets_response.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class CreateMemberWalletsResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Rphaven\Common\V1\GPBMetadata\Correlation::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xC8\x02\x0A4rphaven/gsts/v1/create_member_wallets_response.proto\x12\x0Frphaven.gsts.v1\"_\x0A\x1BCreateMemberWalletsResponse\x12@\x0A\x0Bcorrelation\x18\x01 \x01(\x0B2\x1E.rphaven.common.v1.CorrelationR\x0BcorrelationB\x95\x01\x0A\x13com.rphaven.gsts.v1B CreateMemberWalletsResponseProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

