<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gsts/v1/meet.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class Meet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xB2\x03\x0A\x12gsts/v1/meet.proto\x12\x0Frphaven.gsts.v1\"\x98\x01\x0A\x04Meet\x12\x0E\x0A\x02id\x18\x01 \x01(\x0CR\x02id\x12\x12\x0A\x04name\x18\x02 \x01(\x09R\x04name\x12.\x0A\x05venue\x18\x03 \x01(\x0B2\x16.rphaven.gsts.v1.VenueH\x00R\x05venue\x124\x0A\x07virtual\x18\x04 \x01(\x0B2\x18.rphaven.gsts.v1.VirtualH\x00R\x07virtualB\x06\x0A\x04meet\"]\x0A\x05Venue\x12\x1A\x0A\x08latitude\x18\x01 \x01(\x01R\x08latitude\x12\x1C\x0A\x09longitude\x18\x02 \x01(\x01R\x09longitude\x12\x1A\x0A\x08accuracy\x18\x03 \x01(\x05R\x08accuracy\"\x09\x0A\x07VirtualB~\x0A\x13com.rphaven.gsts.v1B\x09MeetProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

