<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: gsts/v1/subs.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class Subs
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Rphaven\Gsts\V1\GPBMetadata\MemberSub::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x91\x02\x0A\x12gsts/v1/subs.proto\x12\x0Frphaven.gsts.v12b\x0A\x0BSubsService\x12S\x0A\x07Session\x12#.rphaven.gsts.v1.ConsumeMemberToken\x1A!.rphaven.gsts.v1.TokenConsumption\"\x00B~\x0A\x13com.rphaven.gsts.v1B\x09SubsProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

