<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/tokens_consumed.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class TokensConsumed
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Rphaven\Gsts\V1\GPBMetadata\TokenConsumptionTransaction::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xAD\x02\x0A%rphaven/gsts/v1/tokens_consumed.proto\x12\x0Frphaven.gsts.v1\"`\x0A\x0ETokensConsumed\x12N\x0A\x0Btransaction\x18\x01 \x01(\x0B2,.rphaven.gsts.v1.TokenConsumptionTransactionR\x0BtransactionB\x88\x01\x0A\x13com.rphaven.gsts.v1B\x13TokensConsumedProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

