<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/token.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class Token
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Google\Protobuf\Timestamp::initOnce();
        \Rphaven\Gsts\V1\GPBMetadata\TokenSignatuure::initOnce();
        \Rphaven\Common\V1\GPBMetadata\Uid::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBE\x04\x0A\x1Brphaven/gsts/v1/token.proto\x12\x0Frphaven.gsts.v1\x1A&rphaven/gsts/v1/token_signatuure.proto\x1A\x1Brphaven/common/v1/uid.proto\"\xBF\x02\x0A\x05Token\x12&\x0A\x02id\x18\x01 \x01(\x0B2\x16.rphaven.common.v1.UidR\x02id\x122\x0A\x06issued\x18\x02 \x01(\x0B2\x1A.google.protobuf.TimestampR\x06issued\x12!\x0A\x0Cissue_number\x18\x03 \x01(\x11R\x0BissueNumber\x12.\x0A\x06member\x18\x04 \x01(\x0B2\x16.rphaven.common.v1.UidR\x06member\x12=\x0A\x09signature\x18\x05 \x01(\x0B2\x1F.rphaven.gsts.v1.TokenSignatureR\x09signature\x12;\x0A\x08consumed\x18\x06 \x01(\x0B2\x1A.google.protobuf.TimestampH\x00R\x08consumed\x88\x01\x01B\x0B\x0A\x09_consumedB\x7F\x0A\x13com.rphaven.gsts.v1B\x0ATokenProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

