<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/token_signatuure.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class TokenSignatuure
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Rphaven\Common\V1\GPBMetadata\Uid::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\x9D\x02\x0A&rphaven/gsts/v1/token_signatuure.proto\x12\x0Frphaven.gsts.v1\"N\x0A\x0ETokenSignature\x12(\x0A\x03key\x18\x01 \x01(\x0B2\x16.rphaven.common.v1.UidR\x03key\x12\x12\x0A\x04hash\x18\x02 \x01(\x0CR\x04hashB\x89\x01\x0A\x13com.rphaven.gsts.v1B\x14TokenSignatuureProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

