<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/venue_meet.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class VenueMeet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xA4\x02\x0A rphaven/gsts/v1/venue_meet.proto\x12\x0Frphaven.gsts.v1\"a\x0A\x09VenueMeet\x12\x1A\x0A\x08latitude\x18\x01 \x01(\x01R\x08latitude\x12\x1C\x0A\x09longitude\x18\x02 \x01(\x01R\x09longitude\x12\x1A\x0A\x08accuracy\x18\x03 \x01(\x05R\x08accuracyB\x83\x01\x0A\x13com.rphaven.gsts.v1B\x0EVenueMeetProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

