<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/virtual_meet.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class VirtualMeet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            "\x0A\xD4\x01\x0A\"rphaven/gsts/v1/virtual_meet.proto\x12\x0Frphaven.gsts.v1\"\x0D\x0A\x0BVirtualMeetB\x85\x01\x0A\x13com.rphaven.gsts.v1B\x10VirtualMeetProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

