<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/wallet_tokens.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class WalletTokens
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Rphaven\Gsts\V1\GPBMetadata\Wallet::initOnce();
        \Rphaven\Gsts\V1\GPBMetadata\Token::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xEC\x02\x0A#rphaven/gsts/v1/wallet_tokens.proto\x12\x0Frphaven.gsts.v1\x1A\x1Brphaven/gsts/v1/token.proto\"\x85\x01\x0A\x0CWalletTokens\x12/\x0A\x06wallet\x18\x01 \x01(\x0B2\x17.rphaven.gsts.v1.WalletR\x06wallet\x12\x14\x0A\x05total\x18\x02 \x01(\x11R\x05total\x12.\x0A\x06tokens\x18\x03 \x03(\x0B2\x16.rphaven.gsts.v1.TokenR\x06tokensB\x86\x01\x0A\x13com.rphaven.gsts.v1B\x11WalletTokensProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

