<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: rphaven/gsts/v1/wallet.proto

namespace Rphaven\Gsts\V1\GPBMetadata;

class Wallet
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \Rphaven\Gsts\V1\GPBMetadata\Member::initOnce();
        \Rphaven\Common\V1\GPBMetadata\Uid::initOnce();
        $pool->internalAddGeneratedFile(
            "\x0A\xBA\x02\x0A\x1Crphaven/gsts/v1/wallet.proto\x12\x0Frphaven.gsts.v1\x1A\x1Brphaven/common/v1/uid.proto\"a\x0A\x06Wallet\x12&\x0A\x02id\x18\x01 \x01(\x0B2\x16.rphaven.common.v1.UidR\x02id\x12/\x0A\x06member\x18\x02 \x01(\x0B2\x17.rphaven.gsts.v1.MemberR\x06memberB\x80\x01\x0A\x13com.rphaven.gsts.v1B\x0BWalletProtoP\x01\xA2\x02\x03RGX\xAA\x02\x0FRphaven.Gsts.V1\xCA\x02\x0FRphaven\\Gsts\\V1\xE2\x02\x1BRphaven\\Gsts\\V1\\GPBMetadata\xEA\x02\x11Rphaven::Gsts::V1b\x06proto3"
        , true);

        static::$is_initialized = true;
    }
}

